apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-script
data:
  init.js: |
    rs.initiate({
      _id: "rs0",
      members: [
        { _id: 0, host: "mongo-0.mongo:27017" },
        { _id: 1, host: "mongo-1.mongo:27017" }
      ]
    });

    let status;
    do {
      sleep(15000);
      try {
        status = rs.status();
      } catch (e) {
        print("Waiting for primary...");
      }
    } while (!status || status.myState !== 1);

    const admin = db.getSiblingDB('admin');
    admin.createUser({
                        user: 'admin',
                        pwd: 'admin',
                        roles: [{ role: 'root', db: 'admin' }]
                      });

    const mydb = db.getSiblingDB('service');
    mydb.createUser({
                      user: 'admin',
                      pwd: 'admin',
                      roles: [{ role: 'readWrite', db: 'service' }]
                    });

    mydb.createCollection('user');
    mydb.user.createIndex( { 'email': 1 }, { unique: true } )

    mydb.user.insertOne({ email: 'fabiose@email.com', password: 'VGVzdGUxMSE=', activated: true });

    print("Replica set initialized and admin user created.");
