apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-script
data:
  mongo-init.js: |-
    db = db.getSiblingDB('service');

    db.createUser({
      user: "admin",
      pwd: "admin",
      roles: [{
        role: "readWrite",
        db: "service"
      }]
    });

    db.user.createIndex( { "email": 1 }, { unique: true } )

    db.user.insertMany([
      { email: "festrela@email.com", password: 'VGVzdGUxMSE=', activated: true }
    ]);