apiVersion: v1
kind: Secret
metadata:
  name: service-secret
stringData:
  MONGODB_PWD: admin
  JWT_SECRET: 061aa9003c48c120b6613a0636340505cb0dc20f57bd19cc327b412f0c491332
  SENDER_EMAIL_PASSWORD: "your googleapi code"
type: Opaque