apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
  labels:
    app: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
        - name: service
          image: fabiose81/service
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: service-configmap
            - secretRef:
                name: service-secret