apiVersion: apps/v1
kind: Deployment
metadata:
  name: event
  labels:
    app: event
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: event
    spec:
      containers:
        - name: event
          image: fabiose81/event
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: event-configmap